HUDI-1896 intial source for Cloud Dfs
codope/hudi pull request #1
Opened 2021-07-13 05:15 UTC by satishmittal1111

## *Tips*
- *Thank you very much for contributing to Apache Hudi.*
- *Please review https://hudi.apache.org/contributing.html before opening a pull request.*

## What is the purpose of the pull request

*(For example: This pull request adds quick-start document.)*

## Brief change log

*(for example:)*
  - *Modify AnnotationLocation checkstyle rule in checkstyle.xml*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is a trivial rework / code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added integration tests for end-to-end.*
  - *Added HoodieClientWriteTest to verify the change.*
  - *Manually verified the change by running a job locally.*

## Committer checklist

 - [ ] Has a corresponding JIRA in PR title & commit
 
 - [ ] Commit message is descriptive of the change
 
 - [ ] CI is green

 - [ ] Necessary doc changes done or have another open PR
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

2021-07-14 06:56 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +import java.util.*;
nit: can we import specific class/interfaces only?

2021-07-14 06:58 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +        public static final String SQS_QUEUE_URL_PROP = "hoodie.deltastreamer.source.sqs.queueurl";
Can we rename the configs keys to be generic enough for multi clouds? SQS is AWS service, while GCP has its own. Probably, we could have an abstract class which will be extended by AWS/GCP specific classes. What do you think?

2021-07-14 07:00 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +
a serial version id would be good to have like other classes.

2021-07-14 07:01 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +    public static HashMap<String, Boolean> map = new HashMap<>();
nit: perhaps a better name for the map to signify what it holds?

2021-07-14 07:02 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +    protected final TypedProperties props;
Why are all these variables protected?

2021-07-14 07:02 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +    protected final int MaxMessagesEachRequest;
nit: rename to `maxMessagesEachRequest ` and `maxMessageEachBatch `

2021-07-14 07:07 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +        System.out.println("Reading messages....");
let's use logger

2021-07-14 07:12 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +                if (IGNORE_FILEPREFIX_LIST.stream().noneMatch(fileName::startsWith)) {
yeah let's move this to `listFilesAfterCheckpoint ` method as you have mentioned.

2021-07-14 07:12 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +//                    map.put(filePath, Boolean.TRUE);
i'm assuming in the next revision of the PR, we will be using this map.

2021-07-14 07:13 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +}
nit: line break at EOF

2021-07-14 07:14 UTC, codope reviewed
@satishmittal1111 Overall looks good. Few minor comments. Along with them, can you update the PR with the changes that we discussed?

2021-07-20 03:55 UTC, codope commented on hudi-utilities/pom.xml
>  -->
Can we undo this change? Are we adding any new dependency?

2021-07-20 03:57 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/CloudObjectsDfsSource.java
> +        Pair<Option<String>, String> selectPathsWithLatestSQSMessage =
We can rename the variable/methods to be cloud provider agnostic, e.g. rename selectPathsWithLatestSQSMessage to selectPathsWithLatestMessage

2021-07-20 03:58 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/CloudObjectsDfsSource.java
> +}
nit: line break after the class ends.

2021-07-20 04:07 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/CloudObjectsMetaSource.java
> +    public static void main(String[] args) {
Let's remove the main method.

2021-07-20 04:07 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsDfsSelector.java
> +public class CloudObjectsDfsSelector implements Serializable {
I see some commonalities between this and the meta selector. Can we abstract out to a class that can be extended by both?

2021-07-20 04:11 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsMetaSelector.java
> +        public static final String QUEUE_URL_PROP = "hoodie.deltastreamer.source.queue.url";
Few minor comments related to naming of the config keys. Let's discuss offline.

2021-07-20 04:21 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsMetaSelector.java
> +            if (!ineligibleMessages.isEmpty()) {
Let me know if my understanding is incorrect.
Here, we are trying to only delete ineligible messages (the ones that are not with ALLOWED_S3_EVENT_PREFIX). The eligible messages will get deleted later after the DeltaSync#writeToSink has completed. Is that correct?

2021-07-20 04:23 UTC, codope reviewed
First round looks good. Let's discuss the deletion part in a bit more detail offline.

2021-07-27 05:31 UTC, codope commented on hudi-utilities/pom.xml
> +      <dependency>
Let's talk about these dependencies. It's better if we can do without them.

2021-07-27 05:33 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/CloudObjectsHoodieIncrSource.java
> +  @SuppressWarnings("checkstyle:WhitespaceAfter")
Do we need this SuppressWarnings?

2021-07-27 05:34 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/CloudObjectsHoodieIncrSource.java
> +        props, Collections.singletonList(Config.HOODIE_SRC_BASE_PATH));
Are we gonna need other properties to make the connection?

2021-07-27 05:38 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/CloudObjectsHoodieIncrSource.java
> +        "hoodie.deltastreamer.source.hoodieincr.num_instants";
Let's rename this to `hoodie.deltastreamer.source.hoodieincr.num.instants` or `hoodie.deltastreamer.source.hoodieincr.instants`. Idea is to not have underscore, if we need underscore we can replace it by `.` as well.

2021-07-27 05:38 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/CloudObjectsHoodieIncrSource.java
> +    // log.info("Final Schema from Source is :" + src.schema());
nit: remove this log

2021-07-27 05:47 UTC, codope commented on hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelector.java
> +    for (int i = 0;
Let's add a comment why this loop is needed and why we can't use any collection api for partition.

2021-07-27 05:59 UTC, codope requested changes
@satishmittal1111 Can you resolve review comments after you have addressed them? Few more minor changes required as commented below. Please also addd test cases. 

I have one question: why are we not using SNS? My understanding is that we first publish to SNS which pushes to SQS right?

2021-08-01 19:32 UTC, satishmittal1111 commented
@codope I have added the test cases. please review.

2021-08-07 06:18 UTC, codope reviewed
@satishmittal1111 Thanks for working in this. Overall, looks good to me. I'll do some minor changes and then push to a branch other than master so that it can be upstreamed.

2021-08-07 06:21 UTC, merged